name: Main

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://newsapi.org/v2/top-headlines?language=en&pageSize=35&apiKey=${{ secrets.NEWSAPI_KEY }}

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: fetch-api-data-action
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
